name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        platform: ['linux-x64', 'win-x64']
        folder : ['./RemoveBinaries','.\RemoveBinaries']

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET on ${{ matrix.os }} using ${{ matrix.platform }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --project ${{ matrix.folder }} --runtime ${{ matrix.platform }}
      
    
